export const GET_COUNTRIES = 'GET_COUNTRIES'

export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST'
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE'
export const FETCH_SELECTED_COUNTRY = 'FETCH_SELECTED_COUNTRY'
export const POST_COUNTRY = 'POST_COUNTRY'
